name: Setup JFrog CLI with OIDC

on: 
  push:
    tags:
      - "v*" # This triggers the workflow on tags that start with 'v'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: '2.73.0'

      - name: Request GitHub OIDC Token and Configure JFrog CLI
        id: configure-jfrog-cli
        env:
          JFROG_URL: https://hts2.jfrog.io
        run: |
          echo "Configuring JFrog CLI with OIDC..."

          # Request GitHub OIDC token
          token=$(curl -H "Authorization: bearer ${{ steps.configure-jfrog-cli.outputs.id_token }}" \
             "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')

          # Configure JFrog CLI with the OIDC token
          echo "Configuring JFrog CLI..."
          jf c add my-artifactory-server --url=$JFROG_URL --access-token=$token --interactive=false

      - name: Run JFrog CLI
        run: |
          # Ping the server to check the connection
          jf rt ping --server-id=my-artifactory-server
